#!/bin/sh

case `uname -s` in
    FreeBSD)
		libtoolize
    aclocal19
    autoheader259
    automake19 --add-missing --foreign --copy
    autoconf259
    ;;
		Darwin)
		glibtoolize
		aclocal
		autoheader
		automake --add-missing --foreign --copy
		autoconf
		;;
    *)
		libtoolize
    aclocal
    autoheader
    automake --add-missing --foreign --copy
    autoconf
    ;;
esac
